bolsa:
  production:
    web:
      port:         50099
    ssm:
      region:       us-east-1
    mysql:
      host:         mysql/host
      port:         mysql/port
      user:         mysql/user
      password:     mysql/password
      db:           mysql/db
    mongo:
      url:          mongo/url
      db:           mongo/db
    queue:
      region:       queue/region
      url:          queue/url
      wait:         20
    job:
      maxRetries:   4
      retryDelay:   900
      workerCount:  2
    log:
      level:        ERR

  staging:
    web:
      port:         50099
    ssm:
      region:       us-east-1
    mysql:
      host:         mysql/host
      port:         mysql/port
      user:         mysql/user
      password:     mysql/password
      db:           mysql/db
    mongo:
      url:          mongo/url
      db:           mongo/db
    queue:
      region:       queue/region
      url:          queue/url
      wait:         20
    job:
      maxRetries:   4
      retryDelay:   900
      workerCount:  2
    log:
      level:        WARN

  testing:
    web:
      port:         50099
    ssm:
      region:       us-east-1
    mysql:
      host:         mysql/host
      port:         mysql/port
      user:         mysql/user
      password:     mysql/password
      db:           mysql/db
    mongo:
      url:          mongo/url
      db:           mongo/db
    queue:
      region:       queue/region
      url:          queue/url
      wait:         20
    job:
      maxRetries:   4
      retryDelay:   900
      workerCount:  2
    log:
      level:        INFO

  development:
    web:
      port:         50099
    ssm:
      region:       us-east-1
    mysql:
      host:         127.0.0.1
      port:         3306
      user:         test
      password:     test
      db:           mysql_seed
    mongo:
      url:          mongodb://localhost:27017/mongo_seed
      db:           mongo_seed
    queue:
      region:       us-east-1
      url:          https://sqs.us-east-1.amazonaws.com/184310216834/sam-hook-loop
      wait:         20
    job:
      maxRetries:   4
      retryDelay:   900
      workerCount:  2
    log:
      level:        DEBUG
